const WarnedMap: { [key: string]: boolean } = {};
/**
 * @internal
 */
export function _WarnImport(name: string, warnOnce = false) {
    if (warnOnce && WarnedMap[name]) {
        return;
    }
    WarnedMap[name] = true;
    return `${name} needs to be imported before as it contains a side-effect required by your code.`;
}

const _StubWarnedMap: { [key: string]: boolean } = {};

/**
 * Interface for functions that are side-effect stubs.
 * Used to type-safely check if a method is a stub without using `any`.
 * @internal
 */
export interface ISideEffectStub {
    /** Marker property indicating this is a side-effect stub */
    __isSideEffectStub: true;
}

/**
 * Returns a stub function that logs a warning when an augmented method is called
 * without importing its side-effect module. The real implementation overwrites
 * the stub when the corresponding register function is loaded.
 * @internal
 */
export function _MissingSideEffect(className: string, methodName: string): (...args: unknown[]) => void {
    const stub = function () {
        const key = `${className}.${methodName}`;
        if (!_StubWarnedMap[key]) {
            _StubWarnedMap[key] = true;
            // eslint-disable-next-line no-console
            console.warn(`[Babylon.js] ${key}() requires a side-effect import. See: https://doc.babylonjs.com/setup/treeshaking`);
        }
    };
    (stub as unknown as ISideEffectStub).__isSideEffectStub = true;
    return stub;
}

/**
 * Checks whether a value is a side-effect stub (i.e., a placeholder function
 * generated by _MissingSideEffect). Use this instead of truthiness checks when
 * doing feature detection on methods that may be stubbed for tree-shaking.
 * @param fn The function/method to check
 * @returns true if the function is a real implementation (not a stub or undefined/null)
 * @internal
 */
export function _IsSideEffectImplemented(fn: unknown): boolean {
    if (!fn) {
        return false;
    }
    return !(fn as ISideEffectStub).__isSideEffectStub;
}

/**
 * Returns a property descriptor that acts as a placeholder for augmented properties
 * that require a side-effect import. The getter returns undefined (allowing pure code
 * to feature-detect by checking truthiness), and the setter replaces the stub with a
 * real data property on the instance.
 * @internal
 */
export function _MissingSideEffectProperty(className: string, propName: string): PropertyDescriptor {
    return {
        get() {
            return undefined;
        },
        set(value) {
            // Replace the stub with a real data property so the value is stored
            Object.defineProperty(this, propName, {
                value,
                writable: true,
                configurable: true,
                enumerable: true,
            });
        },
        configurable: true,
        enumerable: true,
    };
}
