/// <reference lib="webworker" />
/* eslint-disable @typescript-eslint/naming-convention, github/no-then, @typescript-eslint/promise-function-async */

import { type ImporterModule, type ImporterModuleFactory } from "./usdModule";
import { type ExtractRequest, type WorkerResponse } from "./usdWorkerMessages";

/**
 * Entry point serialized into the USD module worker.
 * @internal
 */
export function USDWorkerFunction(): void {
    let modulePromise: Promise<ImporterModule> | undefined;
    let moduleLocationKey: string | undefined;
    let activeRequestId = 0;
    let queue = Promise.resolve();

    function post(response: WorkerResponse, transfer: Transferable[] = []): void {
        self.postMessage(response, { transfer });
    }

    async function loadModule(glueUrl?: string, wasmUrl?: string, dataUrl?: string): Promise<ImporterModule> {
        const locationKey = `${glueUrl ?? ""}\n${wasmUrl ?? ""}\n${dataUrl ?? ""}`;
        if (modulePromise && moduleLocationKey !== locationKey) {
            modulePromise = undefined;
        }
        if (!modulePromise) {
            moduleLocationKey = locationKey;
            modulePromise = (async () => {
                post({
                    type: "progress",
                    requestId: activeRequestId,
                    progress: { phase: "initializing", message: "Loading OpenUSD..." },
                });
                if (!glueUrl) {
                    throw new Error("The USD importer glue URL was not configured.");
                }
                const moduleUrl = new URL(glueUrl, self.location.href).href;
                const moduleBase = new URL(".", moduleUrl).href;
                // Generated by CMake; the runtime URL may be relocated by the caller.
                const imported = (await import(/* @vite-ignore */ /* webpackIgnore: true */ moduleUrl)) as {
                    default: ImporterModuleFactory;
                };
                return await imported.default({
                    noExitRuntime: true,
                    locateFile: (path) => {
                        if (wasmUrl && path.endsWith(".wasm")) {
                            return wasmUrl;
                        }
                        if (dataUrl && path.endsWith(".data")) {
                            return dataUrl;
                        }
                        return moduleBase + path;
                    },
                });
            })();
            modulePromise.catch(() => {
                modulePromise = undefined;
                moduleLocationKey = undefined;
            });
        }
        return await modulePromise;
    }

    function ensureDirectory(module: ImporterModule, path: string, created?: string[]): void {
        const parts = path.split("/").filter(Boolean);
        let current = "";
        for (const part of parts) {
            current += `/${part}`;
            if (!module.FS.analyzePath(current).exists) {
                module.FS.mkdir(current);
                created?.push(current);
            }
        }
    }

    function parentPath(path: string): string {
        const slash = path.lastIndexOf("/");
        return slash > 0 ? path.slice(0, slash) : "/";
    }

    function normalizedVirtualPath(path: string, label: string): string {
        const normalized = path.replace(/\\/g, "/");
        const parts = normalized.split("/").filter((part) => part && part !== ".");
        if (normalized.startsWith("/") || parts.length === 0 || parts.includes("..")) {
            throw new Error(`${label} must be a relative virtual path.`);
        }
        return parts.join("/");
    }

    async function extract(request: ExtractRequest): Promise<void> {
        activeRequestId = request.requestId;
        const module = await loadModule(request.asset.glueUrl, request.asset.wasmUrl, request.asset.dataUrl);
        module.setLogCallback((level, message) => {
            post({ type: "log", requestId: request.requestId, level, message });
        });

        const root = `/work/${request.requestId}`;
        const createdDirectories: string[] = [];
        ensureDirectory(module, root, createdDirectories);
        const written: string[] = [];
        const writtenPaths = new Set<string>();
        try {
            post({
                type: "progress",
                requestId: request.requestId,
                progress: { phase: "staging", message: `Staging ${request.asset.fileName}...` },
            });
            const inputPath = `${root}/${normalizedVirtualPath(request.asset.fileName, "fileName")}`;
            ensureDirectory(module, parentPath(inputPath), createdDirectories);
            module.FS.writeFile(inputPath, request.asset.bytes);
            written.push(inputPath);
            writtenPaths.add(inputPath);
            for (const [relativePath, bytes] of Object.entries(request.asset.files ?? {})) {
                const path = `${root}/${normalizedVirtualPath(relativePath, "files entry")}`;
                if (writtenPaths.has(path)) {
                    throw new Error(`Duplicate virtual file path '${relativePath}'.`);
                }
                ensureDirectory(module, parentPath(path), createdDirectories);
                module.FS.writeFile(path, bytes);
                written.push(path);
                writtenPaths.add(path);
            }

            module.clearAssetIndex();
            module.setRootAssetPath(inputPath);
            module.setAssetFallbackEnabled(request.asset.resolveByFileName);
            module.registerAssetDirectory(root);
            post({
                type: "progress",
                requestId: request.requestId,
                progress: { phase: "extracting", message: "Extracting the composed USD stage..." },
            });

            const result = module.extract(inputPath);
            try {
                if (!result.ok()) {
                    throw new Error(result.error());
                }
                const copyStarted = performance.now();
                const commands = module.HEAPU8.slice(result.commandPtr(), result.commandPtr() + result.commandSize()).buffer;
                const data = module.HEAPU8.slice(result.dataPtr(), result.dataPtr() + result.dataSize()).buffer;
                const heapCopyMs = performance.now() - copyStarted;
                post(
                    {
                        type: "result",
                        requestId: request.requestId,
                        commands,
                        data,
                        timings: {
                            totalMs: result.totalMs() + heapCopyMs,
                            stageOpenMs: result.stageOpenMs(),
                            stageReadMs: result.stageReadMs(),
                            preparationMs: result.preparationMs(),
                            packingMs: result.packingMs(),
                            heapCopyMs,
                        },
                        statistics: {
                            nodes: result.nodeCount(),
                            meshes: result.meshCount(),
                            analyticPrimitives: result.analyticPrimitiveCount(),
                            instances: result.instanceCount(),
                            materials: result.materialCount(),
                            vertices: result.vertexCount(),
                            triangles: result.triangleCount(),
                            commandBytes: result.commandSize(),
                            dataBytes: result.dataSize(),
                        },
                        missingAssets: module.getUnresolvedAssets().split(",").filter(Boolean),
                    },
                    [commands, data]
                );
            } finally {
                result.delete();
            }
        } finally {
            for (const path of written.reverse()) {
                try {
                    module.FS.unlink(path);
                } catch {
                    // The worker uses a unique directory for each request.
                }
            }
            for (const path of createdDirectories.reverse()) {
                try {
                    module.FS.rmdir(path);
                } catch {
                    // Only directories created for this request are considered.
                }
            }
        }
    }

    self.addEventListener("message", (event: MessageEvent<ExtractRequest>) => {
        queue = queue
            .then(() => extract(event.data))
            .catch((error: unknown) => {
                post({
                    type: "error",
                    requestId: event.data.requestId,
                    message: error instanceof Error ? error.message : String(error),
                    stack: error instanceof Error ? error.stack : undefined,
                });
            });
    });
}
