cmake_minimum_required(VERSION 3.6)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_XM_NO_INTRINSICS_")

set(CANVAS_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../../..")
set(CANVAS_BUILD_LIB_DIR "${CANVAS_ROOT_DIR}/Built/Out/android_${CMAKE_ANDROID_ARCH_ABI}/${CMAKE_BUILD_TYPE}")
