cmake_minimum_required(VERSION 3.6)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_XM_NO_INTRINSICS_")

set(BABYLONNATIVE_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../")
set(BABYLONNATIVE_BUILD_LIB_DIR "${BABYLONNATIVE_ROOT_DIR}/Build/Library/")

