//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ajax.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Ajax.Utilities.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string ContextSeparator {
            get {
                return ResourceManager.GetString("ContextSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback character encoding failed.
        /// </summary>
        internal static string FallbackEncodingFailed {
            get {
                return ResourceManager.GetString("FallbackEncodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON JavaScript nodes encountered during output.
        /// </summary>
        internal static string InvalidJSONOutput {
            get {
                return ResourceManager.GetString("InvalidJSONOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run-time.
        /// </summary>
        internal static string Severity0 {
            get {
                return ResourceManager.GetString("Severity0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coding.
        /// </summary>
        internal static string Severity1 {
            get {
                return ResourceManager.GetString("Severity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string Severity2 {
            get {
                return ResourceManager.GetString("Severity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performance.
        /// </summary>
        internal static string Severity3 {
            get {
                return ResourceManager.GetString("Severity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to improper technique.
        /// </summary>
        internal static string Severity4 {
            get {
                return ResourceManager.GetString("Severity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown ({0}).
        /// </summary>
        internal static string SeverityUnknown {
            get {
                return ResourceManager.GetString("SeverityUnknown", resourceCulture);
            }
        }
    }
}
