import { SceneRecorder } from 'babylonjs/Misc/sceneRecorder';
import { Scene } from 'babylonjs/scene';

export class ReplayRecorder {
    private _sceneRecorder = new SceneRecorder();

    public trackScene(scene: Scene) {
        this._sceneRecorder.track(scene);
    }

    public export() {
     //   let content = "// Code generated by babylon.js Inspector\r\n// Please keep in mind to define the 'scene' variable before using that code\r\n\r\n";

        this._sceneRecorder.getDiff();

       // Tools.Download(new Blob([content]), "pseudo-code.txt");
    }
}