/* eslint-disable @typescript-eslint/naming-convention */
/**
 * Complete categorized list of all known flow graph block class names.
 * Shared between the node list palette and the display manager registration.
 */
export const AllFlowGraphBlocks: { [category: string]: string[] } = {
    Events: [
        "FlowGraphSceneReadyEventBlock",
        "FlowGraphSceneTickEventBlock",
        "FlowGraphMeshPickEventBlock",
        "FlowGraphPointerDownEventBlock",
        "FlowGraphPointerUpEventBlock",
        "FlowGraphPointerMoveEventBlock",
        "FlowGraphPointerOverEventBlock",
        "FlowGraphPointerOutEventBlock",
        "FlowGraphReceiveCustomEventBlock",
        "FlowGraphSendCustomEventBlock",
    ],
    Control_Flow: [
        "FlowGraphBranchBlock",
        "FlowGraphForLoopBlock",
        "FlowGraphWhileLoopBlock",
        "FlowGraphSwitchBlock",
        "FlowGraphSequenceBlock",
        "FlowGraphMultiGateBlock",
        "FlowGraphFlipFlopBlock",
        "FlowGraphDoNBlock",
        "FlowGraphWaitAllBlock",
        "FlowGraphSetDelayBlock",
        "FlowGraphCancelDelayBlock",
        "FlowGraphCallCounterBlock",
        "FlowGraphDebounceBlock",
        "FlowGraphThrottleBlock",
    ],
    Animation: ["FlowGraphPlayAnimationBlock", "FlowGraphStopAnimationBlock", "FlowGraphPauseAnimationBlock", "FlowGraphInterpolationBlock"],
    Math__Constants: ["FlowGraphEBlock", "FlowGraphPIBlock", "FlowGraphInfBlock", "FlowGraphNaNBlock", "FlowGraphRandomBlock"],
    Math__Arithmetic: [
        "FlowGraphAddBlock",
        "FlowGraphSubtractBlock",
        "FlowGraphMultiplyBlock",
        "FlowGraphDivideBlock",
        "FlowGraphModuloBlock",
        "FlowGraphNegationBlock",
        "FlowGraphAbsBlock",
        "FlowGraphSignBlock",
        "FlowGraphMinBlock",
        "FlowGraphMaxBlock",
        "FlowGraphClampBlock",
        "FlowGraphSaturateBlock",
        "FlowGraphMathInterpolationBlock",
        "FlowGraphPowerBlock",
        "FlowGraphSquareRootBlock",
        "FlowGraphCubeRootBlock",
    ],
    Math__Rounding: ["FlowGraphFloorBlock", "FlowGraphCeilBlock", "FlowGraphRoundBlock", "FlowGraphTruncBlock", "FlowGraphFractBlock"],
    Math__Trigonometry: [
        "FlowGraphSinBlock",
        "FlowGraphCosBlock",
        "FlowGraphTanBlock",
        "FlowGraphASinBlock",
        "FlowGraphACosBlock",
        "FlowGraphATanBlock",
        "FlowGraphATan2Block",
        "FlowGraphSinhBlock",
        "FlowGraphCoshBlock",
        "FlowGraphTanhBlock",
        "FlowGraphASinhBlock",
        "FlowGraphACoshBlock",
        "FlowGraphATanhBlock",
        "FlowGraphDegToRadBlock",
        "FlowGraphRadToDegBlock",
    ],
    Math__Logarithmic: ["FlowGraphExponentialBlock", "FlowGraphLogBlock", "FlowGraphLog2Block", "FlowGraphLog10Block"],
    Math__Comparison: [
        "FlowGraphEqualityBlock",
        "FlowGraphLessThanBlock",
        "FlowGraphLessThanOrEqualBlock",
        "FlowGraphGreaterThanBlock",
        "FlowGraphGreaterThanOrEqualBlock",
        "FlowGraphIsNaNBlock",
        "FlowGraphIsInfBlock",
        "FlowGraphConditionalBlock",
    ],
    Vector_and_Matrix: [
        "FlowGraphLengthBlock",
        "FlowGraphNormalizeBlock",
        "FlowGraphDotBlock",
        "FlowGraphCrossBlock",
        "FlowGraphRotate2DBlock",
        "FlowGraphRotate3DBlock",
        "FlowGraphTransposeBlock",
        "FlowGraphDeterminantBlock",
        "FlowGraphInvertMatrixBlock",
        "FlowGraphMatrixMultiplicationBlock",
    ],
    Bitwise: [
        "FlowGraphBitwiseAndBlock",
        "FlowGraphBitwiseOrBlock",
        "FlowGraphBitwiseXorBlock",
        "FlowGraphBitwiseNotBlock",
        "FlowGraphBitwiseLeftShiftBlock",
        "FlowGraphBitwiseRightShiftBlock",
        "FlowGraphLeadingZerosBlock",
        "FlowGraphTrailingZerosBlock",
        "FlowGraphOneBitsCounterBlock",
    ],
    Data_Conversion: [
        "FlowGraphCombineVector2Block",
        "FlowGraphCombineVector3Block",
        "FlowGraphCombineVector4Block",
        "FlowGraphExtractVector2Block",
        "FlowGraphExtractVector3Block",
        "FlowGraphExtractVector4Block",
        "FlowGraphCombineMatrixBlock",
        "FlowGraphExtractMatrixBlock",
        "FlowGraphTransformVectorBlock",
        "FlowGraphTransformCoordinatesBlock",
        "FlowGraphConjugateBlock",
        "FlowGraphAngleBetweenBlock",
        "FlowGraphQuaternionFromAxisAngleBlock",
        "FlowGraphAxisAngleFromQuaternionBlock",
        "FlowGraphQuaternionFromDirectionsBlock",
        "FlowGraphMatrixDecompose",
        "FlowGraphMatrixCompose",
        "FlowGraphBooleanToFloat",
        "FlowGraphBooleanToInt",
        "FlowGraphFloatToBoolean",
        "FlowGraphIntToBoolean",
        "FlowGraphIntToFloat",
        "FlowGraphFloatToInt",
    ],
    Data_Access: [
        "FlowGraphConstantBlock",
        "FlowGraphGetPropertyBlock",
        "FlowGraphSetPropertyBlock",
        "FlowGraphGetVariableBlock",
        "FlowGraphSetVariableBlock",
        "FlowGraphGetAssetBlock",
        "FlowGraphJsonPointerParserBlock",
        "FlowGraphArrayIndexBlock",
        "FlowGraphIndexOfBlock",
        "FlowGraphDataSwitchBlock",
    ],
    Utility: [
        "FlowGraphConsoleLogBlock",
        "FlowGraphEasingBlock",
        "FlowGraphBezierCurveEasing",
        "FlowGraphContextBlock",
        "FlowGraphCodeExecutionBlock",
        "FlowGraphFunctionReference",
        "FlowGraphDebugBlock",
    ],
};

/**
 * Flat array of every block class name.
 * @returns all block names across all categories
 */
export function GetAllBlockNames(): string[] {
    const names: string[] = [];
    for (const cat in AllFlowGraphBlocks) {
        names.push(...AllFlowGraphBlocks[cat]);
    }
    return names;
}
