//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ajax.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CssStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CssStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Ajax.Utilities.Css.CssStrings", typeof(CssStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0} can be collapsed to {1}.
        /// </summary>
        internal static string ColorCanBeCollapsed {
            get {
                return ResourceManager.GetString("ColorCanBeCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal point not followed by numeric digit.
        /// </summary>
        internal static string DecimalNoDigit {
            get {
                return ResourceManager.GetString("DecimalNoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declaration ignored.
        /// </summary>
        internal static string DeclarationIgnored {
            get {
                return ResourceManager.GetString("DeclarationIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string DeclarationIgnoredFormat {
            get {
                return ResourceManager.GetString("DeclarationIgnoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate namespace declaration; already declared &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateNamespaceDeclaration {
            get {
                return ResourceManager.GetString("DuplicateNamespaceDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value contains unnecessary characters: {0} is equivalent to {1}..
        /// </summary>
        internal static string EquivalentNumbers {
            get {
                return ResourceManager.GetString("EquivalentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected charset string, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedCharset {
            get {
                return ResourceManager.GetString("ExpectedCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing curly-brace, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedClosingBrace {
            get {
                return ResourceManager.GetString("ExpectedClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing bracket, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedClosingBracket {
            get {
                return ResourceManager.GetString("ExpectedClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing parenthesis, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedClosingParenthesis {
            get {
                return ResourceManager.GetString("ExpectedClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected colon, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedColon {
            get {
                return ResourceManager.GetString("ExpectedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect comma, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedComma {
            get {
                return ResourceManager.GetString("ExpectedComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected comma or open brace, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedCommaOrOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedCommaOrOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected comma or semi-colon, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedCommaOrSemicolon {
            get {
                return ResourceManager.GetString("ExpectedCommaOrSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of file; invalid input file.
        /// </summary>
        internal static string ExpectedEndOfFile {
            get {
                return ResourceManager.GetString("ExpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected equal sign, found {0}.
        /// </summary>
        internal static string ExpectedEqualSign {
            get {
                return ResourceManager.GetString("ExpectedEqualSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected expression, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedExpression {
            get {
                return ResourceManager.GetString("ExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected function, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedFunction {
            get {
                return ResourceManager.GetString("ExpectedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hex color, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedHexColor {
            get {
                return ResourceManager.GetString("ExpectedHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedIdentifier {
            get {
                return ResourceManager.GetString("ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier or string, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedIdentifierOrString {
            get {
                return ResourceManager.GetString("ExpectedIdentifierOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected import string or uri, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedImport {
            get {
                return ResourceManager.GetString("ExpectedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected media feature, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedMediaFeature {
            get {
                return ResourceManager.GetString("ExpectedMediaFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected media identifier, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedMediaIdentifier {
            get {
                return ResourceManager.GetString("ExpectedMediaIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected media query, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedMediaQuery {
            get {
                return ResourceManager.GetString("ExpectedMediaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected media-query expression, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedMediaQueryExpression {
            get {
                return ResourceManager.GetString("ExpectedMediaQueryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected namespace string or uri, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedNamespace {
            get {
                return ResourceManager.GetString("ExpectedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected number, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedNumber {
            get {
                return ResourceManager.GetString("ExpectedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected open brace, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected opening parenthesis.
        /// </summary>
        internal static string ExpectedOpenParenthesis {
            get {
                return ResourceManager.GetString("ExpectedOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected percentage, &apos;from&apos;, or &apos;to&apos;; found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedPercentageFromOrTo {
            get {
                return ResourceManager.GetString("ExpectedPercentageFromOrTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected calculation product, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedProduct {
            get {
                return ResourceManager.GetString("ExpectedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected progid, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedProgId {
            get {
                return ResourceManager.GetString("ExpectedProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected number or percentage value in rgb function, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedRgbNumberOrPercentage {
            get {
                return ResourceManager.GetString("ExpectedRgbNumberOrPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected selector, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedSelector {
            get {
                return ResourceManager.GetString("ExpectedSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected semi-colon, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedSemicolon {
            get {
                return ResourceManager.GetString("ExpectedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected semicolon or closing curly-brace, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedSemicolonOrClosingBrace {
            get {
                return ResourceManager.GetString("ExpectedSemicolonOrClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected semi-colon or close brace, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedSemicolonOrOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedSemicolonOrOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected calculation sum, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedSum {
            get {
                return ResourceManager.GetString("ExpectedSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected term, found {0}.
        /// </summary>
        internal static string ExpectedTerm {
            get {
                return ResourceManager.GetString("ExpectedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected calculation unit, found &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectedUnit {
            get {
                return ResourceManager.GetString("ExpectedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript error in expression property: {0}.
        /// </summary>
        internal static string ExpressionError {
            get {
                return ResourceManager.GetString("ExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser hack generates invalid CSS.
        /// </summary>
        internal static string HackGeneratesInvalidCss {
            get {
                return ResourceManager.GetString("HackGeneratesInvalidCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash ({0}) not allowed after unary operator.
        /// </summary>
        internal static string HashAfterUnaryNotAllowed {
            get {
                return ResourceManager.GetString("HashAfterUnaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode high-surrogate value (0x{0:x}) not immediately followed by unicode-escaped low-surrogate value.
        /// </summary>
        internal static string HighSurrogateNoLow {
            get {
                return ResourceManager.GetString("HighSurrogateNoLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode high-surrogate value (0x{0:x}) followed by invalid low-surrogate value: 0x{1:x}.
        /// </summary>
        internal static string InvalidLowSurrogate {
            get {
                return ResourceManager.GetString("InvalidLowSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Unicode Range Token: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidUnicodeRange {
            get {
                return ResourceManager.GetString("InvalidUnicodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media queries require a space between &apos;and&apos; and the opening parenthesis: &apos;{0}&apos;.
        /// </summary>
        internal static string MediaQueryRequiresSpace {
            get {
                return ResourceManager.GetString("MediaQueryRequiresSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser.
        /// </summary>
        internal static string ParserSubsystem {
            get {
                return ResourceManager.GetString("ParserSubsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte-order mark at front of source indicates possible encoding issue..
        /// </summary>
        internal static string PossibleCharsetError {
            get {
                return ResourceManager.GetString("PossibleCharsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible cross-browser invalid class name: {0}.
        /// </summary>
        internal static string PossibleInvalidClassName {
            get {
                return ResourceManager.GetString("PossibleInvalidClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;progid:&apos; is an IE-only construct that generates invalid CSS.
        /// </summary>
        internal static string ProgIdIEOnly {
            get {
                return ResourceManager.GetString("ProgIdIEOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        internal static string ScannerSubsystem {
            get {
                return ResourceManager.GetString("ScannerSubsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not allowed after unary operator: &apos;{0}&apos;.
        /// </summary>
        internal static string TokenAfterUnaryNotAllowed {
            get {
                return ResourceManager.GetString("TokenAfterUnaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace used but not declared in a @namespace statement: &apos;{0}&apos;.
        /// </summary>
        internal static string UndeclaredNamespace {
            get {
                return ResourceManager.GetString("UndeclaredNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An underscore is not a valid CSS1 or CSS2 identifier character.
        /// </summary>
        internal static string UnderscoreNotValid {
            get {
                return ResourceManager.GetString("UnderscoreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected at-keyword, found &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedAtKeyword {
            get {
                return ResourceManager.GetString("UnexpectedAtKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset must be very first token in file.
        /// </summary>
        internal static string UnexpectedCharset {
            get {
                return ResourceManager.GetString("UnexpectedCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected dimension: &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedDimension {
            get {
                return ResourceManager.GetString("UnexpectedDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file encountered.
        /// </summary>
        internal static string UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected escape sequence: \{0}.
        /// </summary>
        internal static string UnexpectedEscape {
            get {
                return ResourceManager.GetString("UnexpectedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected function; only calc( or attr( allowed here, found &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedFunction {
            get {
                return ResourceManager.GetString("UnexpectedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected number character: {0}.
        /// </summary>
        internal static string UnexpectedNumberCharacter {
            get {
                return ResourceManager.GetString("UnexpectedNumberCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected string character: {0}.
        /// </summary>
        internal static string UnexpectedStringCharacter {
            get {
                return ResourceManager.GetString("UnexpectedStringCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token, found &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string UnknownCharacterEncoding {
            get {
                return ResourceManager.GetString("UnknownCharacterEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary units on a value of zero.
        /// </summary>
        internal static string UnnecessaryUnits {
            get {
                return ResourceManager.GetString("UnnecessaryUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated comment..
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string: {0}.
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
    }
}
